/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\base.o d:\documents\projects\nim\smport\nimcache\base.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>

#include <stdio.h>
typedef struct base127005 base127005;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct windowptrHEX3Aobjecttype107581 windowptrHEX3Aobjecttype107581;
typedef struct rendererptrHEX3Aobjecttype107582 rendererptrHEX3Aobjecttype107582;
typedef struct fpsmanager121212 fpsmanager121212;
typedef struct event107171 event107171;
typedef struct scenemanager126005 scenemanager126005;
typedef struct TY126006 TY126006;
typedef struct sceneHEX3Aobjecttype123013 sceneHEX3Aobjecttype123013;
typedef struct point107279 point107279;
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  base127005  {
  TNimObject Sup;
NimStringDesc* Name;
NI Fpslimit;
NI Width;
NI Height;
NIM_BOOL Running;
windowptrHEX3Aobjecttype107581* Window;
rendererptrHEX3Aobjecttype107582* Render;
NI Targetwidth;
NI Targetheight;
};
typedef N_CDECL_PTR(windowptrHEX3Aobjecttype107581*, TY118178) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(rendererptrHEX3Aobjecttype107582*, TY117349) (windowptrHEX3Aobjecttype107581* window, int index, int flags);
struct  fpsmanager121212  {
int Framecount;
float Rateticks;
int Baseticks;
int Lastticks;
int Rate;
};
typedef N_CDECL_PTR(void, TY122051) (fpsmanager121212* manager);
typedef N_CDECL_PTR(NI32, TY122058) (fpsmanager121212* manager, int rate);
typedef NU8 TY107356[52];
struct  event107171  {
NI32 Kind;
TY107356 Padding;
};
struct  scenemanager126005  {
  TNimObject Sup;
TY126006* Scenes;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI32, TY118617) (event107171* event);
typedef N_CDECL_PTR(NI32, TY117033) (rendererptrHEX3Aobjecttype107582* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY117661) (rendererptrHEX3Aobjecttype107582* renderer);
typedef N_CDECL_PTR(void, TY117678) (rendererptrHEX3Aobjecttype107582* renderer);
typedef N_CDECL_PTR(int, TY122080) (fpsmanager121212* manager);
typedef N_CDECL_PTR(void, TY117075) (rendererptrHEX3Aobjecttype107582* renderer);
typedef N_CDECL_PTR(void, TY118237) (windowptrHEX3Aobjecttype107581* window);
struct point107279 {
int Field0;
int Field1;
};
typedef N_CDECL_PTR(void, TY117181) (windowptrHEX3Aobjecttype107581* window, int* w, int* h);
struct  windowptrHEX3Aobjecttype107581  {
char dummy;
};
struct  rendererptrHEX3Aobjecttype107582  {
char dummy;
};
struct  sceneHEX3Aobjecttype123013  {
  TNimObject Sup;
};
struct TY126006 {
  TGenericSeq Sup;
  sceneHEX3Aobjecttype123013* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, getwidth_127018)(base127005* self);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, getheight_127033)(base127005* self);
N_NIMCALL(void, setupwindowandrender_127048)(base127005* self);
N_NIMCALL(void, setup_127063)(base127005* self, NimStringDesc* name, NI width, NI height, NI twidth, NI theight);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, setupwindowandrender_127058)(base127005* self);
N_NIMCALL(void, loop_127083)(base127005* self);
N_NIMCALL(void, init_126278)(scenemanager126005* self);
N_NIMCALL(void, load_126243)(scenemanager126005* self, rendererptrHEX3Aobjecttype107582* render);
N_NIMCALL(NIM_BOOL, tobool_107667)(NI32 some);
N_NIMCALL(void, cleanup_127134)(base127005* self);
static N_INLINE(void, destroy_119183)(windowptrHEX3Aobjecttype107581* window);
N_NIMCALL(NimStringDesc*, HEX24_127153)(point107279 x_127157);
N_NIMCALL(void, init_127147)(base127005* self);
N_NIMCALL(void, loop_127129)(base127005* self);
N_NIMCALL(void, cleanup_127142)(base127005* self);
static N_INLINE(point107279, getsize_119153)(windowptrHEX3Aobjecttype107581* window);
extern TFrame* frameptr_16242;
extern TY118178 Dl_118177;
extern TY117349 Dl_117348;
extern TY122051 Dl_122050;
extern TY122058 Dl_122057;
extern event107171 defaultevent_119362;
extern TNimType NTI126005; /* SceneManager */
extern TY118617 Dl_118616;
extern TY117033 Dl_117032;
extern TY117661 Dl_117660;
extern TY117678 Dl_117677;
extern TY122080 Dl_122079;
extern TY117075 Dl_117074;
extern TY118237 Dl_118236;
extern TY117181 Dl_117180;
extern TNimType NTI3211; /* RootObj */
TNimType NTI127005; /* Base */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
extern TNimType NTI138; /* bool */
extern TNimType NTI107548; /* WindowPtr */
extern TNimType NTI107550; /* RendererPtr */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NI, getwidth_127018)(base127005* self) {
	NI result;
	nimfr("getWidth", "base.nim")
	result = 0;
	nimln(16, "base.nim");
	result = (*self).Width;
	popFrame();
	return result;
}

N_NIMCALL(NI, getheight_127033)(base127005* self) {
	NI result;
	nimfr("getHeight", "base.nim")
	result = 0;
	nimln(19, "base.nim");
	result = (*self).Height;
	popFrame();
	return result;
}

N_NIMCALL(void, setupwindowandrender_127048)(base127005* self) {
	nimfr("setupWindowAndRender", "base.nim")
	nimln(22, "base.nim");
	(*self).Window = Dl_118177((*self).Name->data, ((int) 536805376), ((int) 536805376), ((int) ((*self).Width)), ((int) ((*self).Height)), ((int) 4));
	nimln(23, "base.nim");
	(*self).Render = Dl_117348((*self).Window, ((int) -1), ((NI32) 10));
	popFrame();
}

N_NIMCALL(void, setup_127063)(base127005* self, NimStringDesc* name, NI width, NI height, NI twidth, NI theight) {
	nimfr("setup", "base.nim")
	nimln(27, "base.nim");
	unsureAsgnRef((void**) (&(*self).Name), copyString(name));
	nimln(28, "base.nim");
	(*self).Width = width;
	nimln(29, "base.nim");
	(*self).Height = height;
	nimln(30, "base.nim");
	(*self).Running = NIM_FALSE;
	nimln(31, "base.nim");
	(*self).Targetwidth = twidth;
	nimln(32, "base.nim");
	(*self).Targetheight = theight;
	nimln(35, "base.nim");
	setupwindowandrender_127058(self);
	popFrame();
}

N_NIMCALL(void, loop_127083)(base127005* self) {
	fpsmanager121212 fps;
	NI32 LOC1;
	event107171 event;
	NIM_BOOL running;
	scenemanager126005 scenes;
	scenemanager126005 LOC2;
	nimfr("loop", "base.nim")
	memset((void*)(&fps), 0, sizeof(fps));
	nimln(41, "base.nim");
	Dl_122050((&fps));
	nimln(42, "base.nim");
	LOC1 = 0;
	LOC1 = Dl_122057((&fps), ((int) 60));
	nimln(45, "base.nim");
	event = defaultevent_119362;
	nimln(47, "base.nim");
	running = NIM_TRUE;
	memset((void*)(&scenes), 0, sizeof(scenes));
	scenes.Sup.m_type = (&NTI126005);
	nimln(49, "base.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.Sup.m_type = (&NTI126005);
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.Sup.m_type = (&NTI126005);
	memcpy((void*)(&scenes), (NIM_CONST void*)(&LOC2), sizeof(scenes));
	nimln(52, "base.nim");
	init_126278((&scenes));
	nimln(55, "base.nim");
	load_126243((&scenes), (*self).Render);
	{
		nimln(58, "base.nim");
		while (1) {
			NI32 LOC13;
			int LOC14;
			int LOC15;
			nimln(58, "base.nim");
			if (!(running == NIM_TRUE)) goto LA4;
			{
				nimln(61, "base.nim");
				while (1) {
					NI32 LOC7;
					NIM_BOOL LOC8;
					nimln(61, "base.nim");
					nimln(61, "base.nim");
					LOC7 = 0;
					LOC7 = Dl_118616((&event));
					LOC8 = 0;
					LOC8 = tobool_107667(LOC7);
					if (!LOC8) goto LA6;
					nimln(62, "base.nim");
					{
						nimln(62, "base.nim");
						if (!(event.Kind == ((NI32) 256))) goto LA11;
						nimln(63, "base.nim");
						running = NIM_FALSE;
					}
					LA11: ;
				} LA6: ;
			}
			nimln(66, "base.nim");
			LOC13 = 0;
			LOC13 = Dl_117032((*self).Render, ((NU8) 255), ((NU8) 0), ((NU8) 0), ((NU8) 255));
			nimln(67, "base.nim");
			LOC14 = 0;
			LOC14 = Dl_117660((*self).Render);
			nimln(68, "base.nim");
			Dl_117677((*self).Render);
			nimln(70, "base.nim");
			LOC15 = 0;
			LOC15 = Dl_122079((&fps));
		} LA4: ;
	}
	popFrame();
}

static N_INLINE(void, destroy_119183)(windowptrHEX3Aobjecttype107581* window) {
	nimfr("destroy", "sdl2.nim")
	nimln(1662, "sdl2.nim");
	Dl_118236(window);
	popFrame();
}

N_NIMCALL(void, cleanup_127134)(base127005* self) {
	nimfr("cleanUp", "base.nim")
	nimln(74, "base.nim");
	Dl_117074((*self).Render);
	nimln(75, "base.nim");
	destroy_119183((*self).Window);
	popFrame();
}

static N_INLINE(point107279, getsize_119153)(windowptrHEX3Aobjecttype107581* window) {
	point107279 result;
	nimfr("getSize", "sdl2.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(1655, "sdl2.nim");
	Dl_117180(window, (&result.Field0), (&result.Field1));
	popFrame();
	return result;
}

N_NIMCALL(void, init_127147)(base127005* self) {
	point107279 wp;
	NimStringDesc* LOC1;
	nimfr("init", "base.nim")
	nimln(80, "base.nim");
	loop_127129(self);
	nimln(83, "base.nim");
	cleanup_127142(self);
	nimln(85, "base.nim");
	nimln(85, "base.nim");
	wp = getsize_119153((*self).Window);
	nimln(86, "base.nim");
	nimln(86, "base.nim");
	nimln(86, "base.nim");
	LOC1 = 0;
	LOC1 = HEX24_127153(wp);
	printf("%s\015\012", (LOC1)->data);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, HEX00_baseInit)(void) {
	nimfr("base", "base.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_baseDatInit)(void) {
static TNimNode* TMP183[9];
static TNimNode TMP145[10];
NTI127005.size = sizeof(base127005);
NTI127005.kind = 17;
NTI127005.base = (&NTI3211);
TMP183[0] = &TMP145[1];
TMP145[1].kind = 1;
TMP145[1].offset = offsetof(base127005, Name);
TMP145[1].typ = (&NTI149);
TMP145[1].name = "name";
TMP183[1] = &TMP145[2];
TMP145[2].kind = 1;
TMP145[2].offset = offsetof(base127005, Fpslimit);
TMP145[2].typ = (&NTI108);
TMP145[2].name = "fpsLimit";
TMP183[2] = &TMP145[3];
TMP145[3].kind = 1;
TMP145[3].offset = offsetof(base127005, Width);
TMP145[3].typ = (&NTI108);
TMP145[3].name = "width";
TMP183[3] = &TMP145[4];
TMP145[4].kind = 1;
TMP145[4].offset = offsetof(base127005, Height);
TMP145[4].typ = (&NTI108);
TMP145[4].name = "height";
TMP183[4] = &TMP145[5];
TMP145[5].kind = 1;
TMP145[5].offset = offsetof(base127005, Running);
TMP145[5].typ = (&NTI138);
TMP145[5].name = "running";
TMP183[5] = &TMP145[6];
TMP145[6].kind = 1;
TMP145[6].offset = offsetof(base127005, Window);
TMP145[6].typ = (&NTI107548);
TMP145[6].name = "window";
TMP183[6] = &TMP145[7];
TMP145[7].kind = 1;
TMP145[7].offset = offsetof(base127005, Render);
TMP145[7].typ = (&NTI107550);
TMP145[7].name = "render";
TMP183[7] = &TMP145[8];
TMP145[8].kind = 1;
TMP145[8].offset = offsetof(base127005, Targetwidth);
TMP145[8].typ = (&NTI108);
TMP145[8].name = "targetWidth";
TMP183[8] = &TMP145[9];
TMP145[9].kind = 1;
TMP145[9].offset = offsetof(base127005, Targetheight);
TMP145[9].typ = (&NTI108);
TMP145[9].name = "targetHeight";
TMP145[0].len = 9; TMP145[0].kind = 2; TMP145[0].sons = &TMP183[0];
NTI127005.node = &TMP145[0];
}

