/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\levelscene.o d:\documents\projects\nim\smport\nimcache\levelscene.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct levelsceneHEX3Aobjecttype123006 levelsceneHEX3Aobjecttype123006;
typedef struct rendererptrHEX3Aobjecttype106582 rendererptrHEX3Aobjecttype106582;
typedef struct sceneHEX3Aobjecttype120016 sceneHEX3Aobjecttype120016;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct rect106281 rect106281;
typedef struct textureptrHEX3Aobjecttype106583 textureptrHEX3Aobjecttype106583;
typedef struct event106171 event106171;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  sceneHEX3Aobjecttype120016  {
  TNimObject Sup;
};
struct rect106281 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  levelsceneHEX3Aobjecttype123006  {
  sceneHEX3Aobjecttype120016 Sup;
rect106281 Drect;
rect106281 Srect;
textureptrHEX3Aobjecttype106583* Myimage;
};
typedef N_CDECL_PTR(textureptrHEX3Aobjecttype106583*, TY122253) (rendererptrHEX3Aobjecttype106582* renderer, NCSTRING file);
typedef NU8 TY106356[52];
struct  event106171  {
NI32 Kind;
TY106356 Padding;
};
typedef N_CDECL_PTR(NI32, TY116623) (rendererptrHEX3Aobjecttype106582* renderer, textureptrHEX3Aobjecttype106583* texture, rect106281* srcrect, rect106281* dstrect);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  rendererptrHEX3Aobjecttype106582  {
char dummy;
};
struct  textureptrHEX3Aobjecttype106583  {
char dummy;
};
N_NIMCALL(void, load_123014)(levelsceneHEX3Aobjecttype123006* self, rendererptrHEX3Aobjecttype106582* render);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, events_123038)(levelsceneHEX3Aobjecttype123006* self, event106171* e);
N_NIMCALL(void, update_123048)(levelsceneHEX3Aobjecttype123006* self, NF dt);
N_NIMCALL(void, draw_123058)(levelsceneHEX3Aobjecttype123006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, TMP168)(void* p, NI op);
NIM_CONST rect106281 TMP159 = {((int) 0),
((int) 0),
((int) 101),
((int) 84)}
;
extern TY122253 Dl_122252;
extern TFrame* frameptr_16242;
extern TY116623 Dl_116622;
extern TNimType NTI120016; /* Scene:ObjectType */
TNimType NTI123006; /* LevelScene:ObjectType */
extern TNimType NTI106281; /* Rect */
extern TNimType NTI106552; /* TexturePtr */
TNimType NTI123005; /* LevelScene */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, load_123014)(levelsceneHEX3Aobjecttype123006* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("load", "levelscene.nim")
	nimln(10, "levelscene.nim");
	(*self).Myimage = Dl_122252(render, "assets/mb1.png");
	nimln(11, "levelscene.nim");
	(*self).Drect = TMP159;
	nimln(12, "levelscene.nim");
	(*self).Srect = TMP159;
	popFrame();
}

N_NIMCALL(void, events_123038)(levelsceneHEX3Aobjecttype123006* self, event106171* e) {
	nimfr("events", "levelscene.nim")
	popFrame();
}

N_NIMCALL(void, update_123048)(levelsceneHEX3Aobjecttype123006* self, NF dt) {
	nimfr("update", "levelscene.nim")
	popFrame();
}

N_NIMCALL(void, draw_123058)(levelsceneHEX3Aobjecttype123006* self, rendererptrHEX3Aobjecttype106582* render) {
	NI32 LOC1;
	nimfr("draw", "levelscene.nim")
	nimln(27, "levelscene.nim");
	nimln(27, "levelscene.nim");
	LOC1 = 0;
	LOC1 = Dl_116622(render, (*self).Myimage, (&(*self).Srect), (&(*self).Drect));
	popFrame();
}
N_NIMCALL(void, TMP168)(void* p, NI op) {
	levelsceneHEX3Aobjecttype123006* a;
	a = (levelsceneHEX3Aobjecttype123006*)p;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_levelsceneInit)(void) {
	nimfr("levelscene", "levelscene.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_levelsceneDatInit)(void) {
static TNimNode* TMP166[3];
static TNimNode TMP152[4];
NTI123006.size = sizeof(levelsceneHEX3Aobjecttype123006);
NTI123006.kind = 17;
NTI123006.base = (&NTI120016);
NTI123006.flags = 1;
TMP166[0] = &TMP152[1];
TMP152[1].kind = 1;
TMP152[1].offset = offsetof(levelsceneHEX3Aobjecttype123006, Drect);
TMP152[1].typ = (&NTI106281);
TMP152[1].name = "drect";
TMP166[1] = &TMP152[2];
TMP152[2].kind = 1;
TMP152[2].offset = offsetof(levelsceneHEX3Aobjecttype123006, Srect);
TMP152[2].typ = (&NTI106281);
TMP152[2].name = "srect";
TMP166[2] = &TMP152[3];
TMP152[3].kind = 1;
TMP152[3].offset = offsetof(levelsceneHEX3Aobjecttype123006, Myimage);
TMP152[3].typ = (&NTI106552);
TMP152[3].name = "myimage";
TMP152[0].len = 3; TMP152[0].kind = 2; TMP152[0].sons = &TMP166[0];
NTI123006.node = &TMP152[0];
NTI123005.size = sizeof(levelsceneHEX3Aobjecttype123006*);
NTI123005.kind = 22;
NTI123005.base = (&NTI123006);
NTI123005.marker = TMP168;
}

