/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\scenemanager.o d:\documents\projects\nim\smport\nimcache\scenemanager.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct scenemanagerHEX3Aobjecttype124006 scenemanagerHEX3Aobjecttype124006;
typedef struct rendererptrHEX3Aobjecttype106582 rendererptrHEX3Aobjecttype106582;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TY124007 TY124007;
typedef struct sceneHEX3Aobjecttype120016 sceneHEX3Aobjecttype120016;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct event106171 event106171;
typedef struct tcell45146 tcell45146;
typedef struct tcellseq45162 tcellseq45162;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset45158 tcellset45158;
typedef struct tpagedesc45154 tpagedesc45154;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47014 tgcstat47014;
typedef struct levelsceneHEX3Aobjecttype123006 levelsceneHEX3Aobjecttype123006;
typedef struct rect106281 rect106281;
typedef struct textureptrHEX3Aobjecttype106583 textureptrHEX3Aobjecttype106583;
typedef struct mysceneHEX3Aobjecttype121011 mysceneHEX3Aobjecttype121011;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  scenemanagerHEX3Aobjecttype124006  {
  TNimObject Sup;
TY124007* Scenes;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 TY106356[52];
struct  event106171  {
NI32 Kind;
TY106356 Padding;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  tcell45146  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45162  {
NI Len;
NI Cap;
tcell45146** D;
};
struct  tcellset45158  {
NI Counter;
NI Max;
tpagedesc45154* Head;
tpagedesc45154** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45162 Zct;
tcellseq45162 Decstack;
tcellset45158 Cycleroots;
tcellseq45162 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47014 Stat;
};
struct  sceneHEX3Aobjecttype120016  {
  TNimObject Sup;
};
struct rect106281 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  levelsceneHEX3Aobjecttype123006  {
  sceneHEX3Aobjecttype120016 Sup;
rect106281 Drect;
rect106281 Srect;
textureptrHEX3Aobjecttype106583* Myimage;
};
struct  mysceneHEX3Aobjecttype121011  {
  sceneHEX3Aobjecttype120016 Sup;
NimStringDesc* Customvar;
};
struct  rendererptrHEX3Aobjecttype106582  {
char dummy;
};
typedef NI TY26620[16];
struct  tpagedesc45154  {
tpagedesc45154* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  textureptrHEX3Aobjecttype106583  {
char dummy;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct TY124007 {
  TGenericSeq Sup;
  sceneHEX3Aobjecttype120016* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, load_124013)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, load_120029)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_86421)(NimStringDesc* msg);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, update_124246)(scenemanagerHEX3Aobjecttype124006* self, NF dt);
N_NIMCALL(void, update_120055)(sceneHEX3Aobjecttype120016* self, NF dt);
N_NIMCALL(void, draw_124296)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, draw_120068)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, events_124346)(scenemanagerHEX3Aobjecttype124006* self, event106171* e);
N_NIMCALL(void, events_120042)(sceneHEX3Aobjecttype120016* self, event106171* e);
N_NIMCALL(void, init_124396)(scenemanagerHEX3Aobjecttype124006* self);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP165)(void* p, NI op);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_50604)(tcell45146* c);
static N_INLINE(void, rtladdzct_50204)(tcell45146* c);
N_NOINLINE(void, addzct_48617)(tcellseq45162* s, tcell45146* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell45146* c);
static N_INLINE(void, rtladdcycleroot_49425)(tcell45146* c);
N_NOINLINE(void, incl_45867)(tcellset45158* s, tcell45146* cell);
static N_INLINE(tcell45146*, usrtocell_48646)(void* usr);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51023)(tcell45146* c);
N_NIMCALL(void, TMP171)(void* p, NI op);
STRING_LITERAL(TMP163, "(system.len|system.len|system.len|system.len|system.len|system."
"len|...)(a) (system.==|system.==|system.==|system.==|system.==|s"
"ystem.==|system.==|system.==|system.==|system.==|system.==|syste"
"m.==|system.==|system.==|system.==|system.==|system.==|system.=="
"|system.==|system.==|...)\015\012    L seq modified while iterating ov"
"er it", 324);
extern TFrame* frameptr_16242;
extern TNimType NTI120015; /* Scene */
TNimType NTI124007; /* seq[Scene] */
extern tgcheap47016 gch_47044;
extern TNimType NTI123005; /* LevelScene */
extern TNimType NTI123006; /* LevelScene:ObjectType */
extern TNimType NTI121010; /* MyScene */
extern TNimType NTI121011; /* MyScene:ObjectType */
extern TNimType NTI3411; /* RootObj */
TNimType NTI124006; /* SceneManager:ObjectType */
TNimType NTI124005; /* SceneManager */

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, load_124013)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("load", "scenemanager.nim")
	nimln(10, "scenemanager.nim");
	{
		nimln(10, "scenemanager.nim");
		nimln(10, "scenemanager.nim");
		if (!(0 < (*self).Scenes->Sup.len)) goto LA3;
		{
			sceneHEX3Aobjecttype120016* s_124220;
			TY124007* HEX3Atmp_124222;
			NI i_124225;
			NI l_124227;
			s_124220 = 0;
			HEX3Atmp_124222 = 0;
			nimln(11, "scenemanager.nim");
			HEX3Atmp_124222 = (*self).Scenes;
			nimln(3052, "system.nim");
			i_124225 = 0;
			nimln(3053, "system.nim");
			nimln(3053, "system.nim");
			l_124227 = HEX3Atmp_124222->Sup.len;
			{
				nimln(3054, "system.nim");
				while (1) {
					nimln(3054, "system.nim");
					if (!(i_124225 < l_124227)) goto LA7;
					nimln(3055, "system.nim");
					if ((NU)(i_124225) >= (NU)(HEX3Atmp_124222->Sup.len)) raiseIndexError();
					s_124220 = HEX3Atmp_124222->data[i_124225];
					nimln(12, "scenemanager.nim");
					load_120029(s_124220, render);
					nimln(3056, "system.nim");
					i_124225 = addInt(i_124225, 1);
					nimln(3057, "system.nim");
					{
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						if (!!((HEX3Atmp_124222->Sup.len == l_124227))) goto LA10;
						nimln(3057, "system.nim");
						failedassertimpl_86421(((NimStringDesc*) &TMP163));
					}
					LA10: ;
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, update_124246)(scenemanagerHEX3Aobjecttype124006* self, NF dt) {
	nimfr("update", "scenemanager.nim")
	nimln(15, "scenemanager.nim");
	{
		nimln(15, "scenemanager.nim");
		nimln(15, "scenemanager.nim");
		if (!(0 < (*self).Scenes->Sup.len)) goto LA3;
		{
			sceneHEX3Aobjecttype120016* s_124270;
			TY124007* HEX3Atmp_124272;
			NI i_124275;
			NI l_124277;
			s_124270 = 0;
			HEX3Atmp_124272 = 0;
			nimln(16, "scenemanager.nim");
			HEX3Atmp_124272 = (*self).Scenes;
			nimln(3052, "system.nim");
			i_124275 = 0;
			nimln(3053, "system.nim");
			nimln(3053, "system.nim");
			l_124277 = HEX3Atmp_124272->Sup.len;
			{
				nimln(3054, "system.nim");
				while (1) {
					nimln(3054, "system.nim");
					if (!(i_124275 < l_124277)) goto LA7;
					nimln(3055, "system.nim");
					if ((NU)(i_124275) >= (NU)(HEX3Atmp_124272->Sup.len)) raiseIndexError();
					s_124270 = HEX3Atmp_124272->data[i_124275];
					nimln(17, "scenemanager.nim");
					update_120055(s_124270, dt);
					nimln(3056, "system.nim");
					i_124275 = addInt(i_124275, 1);
					nimln(3057, "system.nim");
					{
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						if (!!((HEX3Atmp_124272->Sup.len == l_124277))) goto LA10;
						nimln(3057, "system.nim");
						failedassertimpl_86421(((NimStringDesc*) &TMP163));
					}
					LA10: ;
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, draw_124296)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("draw", "scenemanager.nim")
	nimln(20, "scenemanager.nim");
	{
		nimln(20, "scenemanager.nim");
		nimln(20, "scenemanager.nim");
		if (!(0 < (*self).Scenes->Sup.len)) goto LA3;
		{
			sceneHEX3Aobjecttype120016* s_124320;
			TY124007* HEX3Atmp_124322;
			NI i_124325;
			NI l_124327;
			s_124320 = 0;
			HEX3Atmp_124322 = 0;
			nimln(21, "scenemanager.nim");
			HEX3Atmp_124322 = (*self).Scenes;
			nimln(3052, "system.nim");
			i_124325 = 0;
			nimln(3053, "system.nim");
			nimln(3053, "system.nim");
			l_124327 = HEX3Atmp_124322->Sup.len;
			{
				nimln(3054, "system.nim");
				while (1) {
					nimln(3054, "system.nim");
					if (!(i_124325 < l_124327)) goto LA7;
					nimln(3055, "system.nim");
					if ((NU)(i_124325) >= (NU)(HEX3Atmp_124322->Sup.len)) raiseIndexError();
					s_124320 = HEX3Atmp_124322->data[i_124325];
					nimln(22, "scenemanager.nim");
					draw_120068(s_124320, render);
					nimln(3056, "system.nim");
					i_124325 = addInt(i_124325, 1);
					nimln(3057, "system.nim");
					{
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						if (!!((HEX3Atmp_124322->Sup.len == l_124327))) goto LA10;
						nimln(3057, "system.nim");
						failedassertimpl_86421(((NimStringDesc*) &TMP163));
					}
					LA10: ;
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, events_124346)(scenemanagerHEX3Aobjecttype124006* self, event106171* e) {
	nimfr("events", "scenemanager.nim")
	nimln(25, "scenemanager.nim");
	{
		nimln(25, "scenemanager.nim");
		nimln(25, "scenemanager.nim");
		if (!(0 < (*self).Scenes->Sup.len)) goto LA3;
		{
			sceneHEX3Aobjecttype120016* s_124370;
			TY124007* HEX3Atmp_124372;
			NI i_124375;
			NI l_124377;
			s_124370 = 0;
			HEX3Atmp_124372 = 0;
			nimln(26, "scenemanager.nim");
			HEX3Atmp_124372 = (*self).Scenes;
			nimln(3052, "system.nim");
			i_124375 = 0;
			nimln(3053, "system.nim");
			nimln(3053, "system.nim");
			l_124377 = HEX3Atmp_124372->Sup.len;
			{
				nimln(3054, "system.nim");
				while (1) {
					nimln(3054, "system.nim");
					if (!(i_124375 < l_124377)) goto LA7;
					nimln(3055, "system.nim");
					if ((NU)(i_124375) >= (NU)(HEX3Atmp_124372->Sup.len)) raiseIndexError();
					s_124370 = HEX3Atmp_124372->data[i_124375];
					nimln(27, "scenemanager.nim");
					events_120042(s_124370, e);
					nimln(3056, "system.nim");
					i_124375 = addInt(i_124375, 1);
					nimln(3057, "system.nim");
					{
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						nimln(3057, "system.nim");
						if (!!((HEX3Atmp_124372->Sup.len == l_124377))) goto LA10;
						nimln(3057, "system.nim");
						failedassertimpl_86421(((NimStringDesc*) &TMP163));
					}
					LA10: ;
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}
N_NIMCALL(void, TMP165)(void* p, NI op) {
	TY124007* a;
	NI LOC1;
	a = (TY124007*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}

static N_INLINE(void, rtladdzct_50204)(tcell45146* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell45146* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49425)(tcell45146* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45867((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell45146* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49425(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(tcell45146*, usrtocell_48646)(void* usr) {
	tcell45146* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45146*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45146))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunref)(void* p) {
	tcell45146* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(223, "gc.nim");
	nimln(223, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_48646(p);
	decref_50604(LOC1);
	popFrame();
}

static N_INLINE(void, incref_51023)(tcell45146* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48667(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49425(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45146* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48646(src);
		incref_51023(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45146* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48646((*dest));
		decref_50604(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, init_124396)(scenemanagerHEX3Aobjecttype124006* self) {
	levelsceneHEX3Aobjecttype123006* levelscene;
	levelsceneHEX3Aobjecttype123006* LOC1;
	mysceneHEX3Aobjecttype121011* myscene;
	mysceneHEX3Aobjecttype121011* LOC2;
	sceneHEX3Aobjecttype120016* LOC3;
	sceneHEX3Aobjecttype120016* LOC4;
	nimfr("init", "scenemanager.nim")
	nimln(30, "scenemanager.nim");
	if ((*self).Scenes) nimGCunref((*self).Scenes);
	(*self).Scenes = (TY124007*) newSeqRC1((&NTI124007), 0);
	nimln(31, "scenemanager.nim");
	LOC1 = 0;
	LOC1 = (levelsceneHEX3Aobjecttype123006*) newObj((&NTI123005), sizeof(levelsceneHEX3Aobjecttype123006));
	(*LOC1).Sup.Sup.m_type = (&NTI123006);
	levelscene = LOC1;
	nimln(32, "scenemanager.nim");
	LOC2 = 0;
	LOC2 = (mysceneHEX3Aobjecttype121011*) newObj((&NTI121010), sizeof(mysceneHEX3Aobjecttype121011));
	(*LOC2).Sup.Sup.m_type = (&NTI121011);
	myscene = LOC2;
	nimln(33, "scenemanager.nim");
	LOC3 = 0;
	LOC3 = &levelscene->Sup;
	(*self).Scenes = (TY124007*) incrSeq(&((*self).Scenes)->Sup, sizeof(sceneHEX3Aobjecttype120016*));
	asgnRef((void**) (&(*self).Scenes->data[(*self).Scenes->Sup.len-1]), LOC3);
	nimln(34, "scenemanager.nim");
	LOC4 = 0;
	LOC4 = &myscene->Sup;
	(*self).Scenes = (TY124007*) incrSeq(&((*self).Scenes)->Sup, sizeof(sceneHEX3Aobjecttype120016*));
	asgnRef((void**) (&(*self).Scenes->data[(*self).Scenes->Sup.len-1]), LOC4);
	popFrame();
}
N_NIMCALL(void, TMP171)(void* p, NI op) {
	scenemanagerHEX3Aobjecttype124006* a;
	a = (scenemanagerHEX3Aobjecttype124006*)p;
	nimGCvisit((void*)(*a).Scenes, op);
}
NIM_EXTERNC N_NOINLINE(void, HEX00_scenemanagerInit)(void) {
	nimfr("scenemanager", "scenemanager.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_scenemanagerDatInit)(void) {
static TNimNode TMP145[1];
NTI124007.size = sizeof(TY124007*);
NTI124007.kind = 24;
NTI124007.base = (&NTI120015);
NTI124007.marker = TMP165;
NTI124006.size = sizeof(scenemanagerHEX3Aobjecttype124006);
NTI124006.kind = 17;
NTI124006.base = (&NTI3411);
TMP145[0].kind = 1;
TMP145[0].offset = offsetof(scenemanagerHEX3Aobjecttype124006, Scenes);
TMP145[0].typ = (&NTI124007);
TMP145[0].name = "scenes";
NTI124006.node = &TMP145[0];
NTI124005.size = sizeof(scenemanagerHEX3Aobjecttype124006*);
NTI124005.kind = 22;
NTI124005.base = (&NTI124006);
NTI124005.marker = TMP171;
}

