/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\scene.o d:\documents\projects\nim\smport\nimcache\scene.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct sceneHEX3Aobjecttype120016 sceneHEX3Aobjecttype120016;
typedef struct rendererptrHEX3Aobjecttype106582 rendererptrHEX3Aobjecttype106582;
typedef struct event106171 event106171;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TNimObject TNimObject;
typedef NU8 TY106356[52];
struct  event106171  {
NI32 Kind;
TY106356 Padding;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  sceneHEX3Aobjecttype120016  {
  TNimObject Sup;
};
struct  rendererptrHEX3Aobjecttype106582  {
char dummy;
};
N_NIMCALL(void, load_120021)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, events_120034)(sceneHEX3Aobjecttype120016* self, event106171* e);
N_NIMCALL(void, update_120047)(sceneHEX3Aobjecttype120016* self, NF dt);
N_NIMCALL(void, draw_120060)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, TMP164)(void* p, NI op);
extern TFrame* frameptr_16242;
extern TNimType NTI3411; /* RootObj */
TNimType NTI120016; /* Scene:ObjectType */
TNimType NTI120015; /* Scene */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, load_120021)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("load", "scene.nim")
	popFrame();
}

N_NIMCALL(void, events_120034)(sceneHEX3Aobjecttype120016* self, event106171* e) {
	nimfr("events", "scene.nim")
	popFrame();
}

N_NIMCALL(void, update_120047)(sceneHEX3Aobjecttype120016* self, NF dt) {
	nimfr("update", "scene.nim")
	popFrame();
}

N_NIMCALL(void, draw_120060)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("draw", "scene.nim")
	popFrame();
}
N_NIMCALL(void, TMP164)(void* p, NI op) {
	sceneHEX3Aobjecttype120016* a;
	a = (sceneHEX3Aobjecttype120016*)p;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_sceneInit)(void) {
	nimfr("scene", "scene.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_sceneDatInit)(void) {
static TNimNode TMP147[1];
NTI120016.size = sizeof(sceneHEX3Aobjecttype120016);
NTI120016.kind = 17;
NTI120016.base = (&NTI3411);
NTI120016.flags = 1;
TMP147[0].len = 0; TMP147[0].kind = 2;
NTI120016.node = &TMP147[0];
NTI120015.size = sizeof(sceneHEX3Aobjecttype120016*);
NTI120015.kind = 22;
NTI120015.base = (&NTI120016);
NTI120015.marker = TMP164;
}

