/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\sdl2_gfx.o d:\documents\projects\nim\smport\nimcache\sdl2_gfx.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct rendererptrHEX3Aobjecttype107582 rendererptrHEX3Aobjecttype107582;
typedef struct surface108300 surface108300;
typedef struct fpsmanager121212 fpsmanager121212;
typedef struct TY13206 TY13206;
typedef struct pixelformat108294 pixelformat108294;
typedef struct rect107281 rect107281;
typedef struct blitmapptrHEX3Aobjecttype108342 blitmapptrHEX3Aobjecttype108342;
typedef struct palette108292 palette108292;
typedef struct color108290 color108290;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY121229) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NU32 color);
typedef N_CDECL_PTR(NI32, TY121238) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121250) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 x2, NI16 y, NU32 color);
typedef N_CDECL_PTR(NI32, TY121260) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 x2, NI16 y, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121273) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y1, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121283) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y1, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121296) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121307) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121321) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121333) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121348) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121359) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121373) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121385) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121400) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121411) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121425) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU32 color);
typedef N_CDECL_PTR(NI32, TY121436) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121450) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 width, NU32 color);
typedef N_CDECL_PTR(NI32, TY121462) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NU8 width, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121477) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121487) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121500) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU32 color);
typedef N_CDECL_PTR(NI32, TY121512) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121527) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NU32 color);
typedef N_CDECL_PTR(NI32, TY121537) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121550) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 r, NU32 color);
typedef N_CDECL_PTR(NI32, TY121560) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121573) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU32 color);
typedef N_CDECL_PTR(NI32, TY121584) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121598) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU32 color);
typedef N_CDECL_PTR(NI32, TY121609) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121623) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU32 color);
typedef N_CDECL_PTR(NI32, TY121634) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rx, NI16 ry, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121648) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU32 color);
typedef N_CDECL_PTR(NI32, TY121660) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121675) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU32 color);
typedef N_CDECL_PTR(NI32, TY121687) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NI16 rad, NI16 start, NI16 finish, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121702) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU32 color);
typedef N_CDECL_PTR(NI32, TY121715) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121731) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU32 color);
typedef N_CDECL_PTR(NI32, TY121744) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121760) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU32 color);
typedef N_CDECL_PTR(NI32, TY121773) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x1, NI16 y1, NI16 x2, NI16 y2, NI16 x3, NI16 y3, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121789) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, NU32 color);
typedef N_CDECL_PTR(NI32, TY121801) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121816) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, NU32 color);
typedef N_CDECL_PTR(NI32, TY121828) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121843) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, NU32 color);
typedef N_CDECL_PTR(NI32, TY121855) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121870) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, surface108300* texture, int texturedx, int texturedy);
typedef N_CDECL_PTR(NI32, TY121884) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, int s, NU32 color);
typedef N_CDECL_PTR(NI32, TY121896) (rendererptrHEX3Aobjecttype107582* renderer, NI16* vx, NI16* vy, int n, int s, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(void, TY121911) (void* fontdata, NU32 cw, NU32 ch);
typedef N_CDECL_PTR(void, TY121919) (NU32 rotation);
typedef N_CDECL_PTR(NI32, TY121925) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NIM_CHAR c, NU32 color);
typedef N_CDECL_PTR(NI32, TY121935) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NIM_CHAR c, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(NI32, TY121948) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NCSTRING s, NU32 color);
typedef N_CDECL_PTR(NI32, TY121958) (rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NCSTRING s, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(surface108300*, TY121971) (surface108300* src, double angle, double zoom, int smooth);
typedef N_CDECL_PTR(surface108300*, TY121980) (surface108300* src, double angle, double zoomx, double zoomy, int smooth);
typedef N_CDECL_PTR(void, TY121990) (int width, int height, double angle, double zoom, int* dstwidth, int* dstheight);
typedef N_CDECL_PTR(void, TY122002) (int width, int height, double angle, double zoomx, double zoomy, int* dstwidth, int* dstheight);
typedef N_CDECL_PTR(surface108300*, TY122015) (surface108300* src, double zoomx, double zoomy, int smooth);
typedef N_CDECL_PTR(void, TY122024) (int width, int height, double zoomx, double zoomy, int* dstwidth, int* dstheight);
typedef N_CDECL_PTR(surface108300*, TY122036) (surface108300* src, int factorx, int factory);
typedef N_CDECL_PTR(surface108300*, TY122044) (surface108300* src, int numclockwiseturns);
typedef N_CDECL_PTR(void, TY122051) (fpsmanager121212* manager);
typedef N_CDECL_PTR(NI32, TY122058) (fpsmanager121212* manager, int rate);
typedef N_CDECL_PTR(int, TY122066) (fpsmanager121212* manager);
typedef N_CDECL_PTR(int, TY122073) (fpsmanager121212* manager);
typedef N_CDECL_PTR(int, TY122080) (fpsmanager121212* manager);
struct  rendererptrHEX3Aobjecttype107582  {
char dummy;
};
struct rect107281 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  surface108300  {
NU32 Flags;
pixelformat108294* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect107281 Cliprect;
blitmapptrHEX3Aobjecttype108342* Map;
int Refcount;
};
struct  fpsmanager121212  {
int Framecount;
float Rateticks;
int Baseticks;
int Lastticks;
int Rate;
};
typedef NU8 TY108324[2];
struct  pixelformat108294  {
NU32 Format;
palette108292* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY108324 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat108294* Next;
};
struct  blitmapptrHEX3Aobjecttype108342  {
char dummy;
};
struct  palette108292  {
int Ncolors;
color108290* Colors;
NU32 Version;
int Refcount;
};
struct color108290 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
struct TY13206 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
N_NIMCALL(void, mlstringrgba_122092)(rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NimStringDesc* s, NU8 r, NU8 g, NU8 b, NU8 a, NI16 linespacing);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start_74828, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_18801)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, mlstringrgba_122145)(rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, TY13206* s, NU8 r, NU8 g, NU8 b, NU8 a, NI16 linespacing);
STRING_LITERAL(TMP150, "SDL2_gfx.dll", 12);
STRING_LITERAL(TMP151, "SDL2_gfx.dll", 12);
static void* TMP149;
TY121229 Dl_121228;
TY121238 Dl_121237;
TY121250 Dl_121249;
TY121260 Dl_121259;
TY121273 Dl_121272;
TY121283 Dl_121282;
TY121296 Dl_121295;
TY121307 Dl_121306;
TY121321 Dl_121320;
TY121333 Dl_121332;
TY121348 Dl_121347;
TY121359 Dl_121358;
TY121373 Dl_121372;
TY121385 Dl_121384;
TY121400 Dl_121399;
TY121411 Dl_121410;
TY121425 Dl_121424;
TY121436 Dl_121435;
TY121450 Dl_121449;
TY121462 Dl_121461;
TY121477 Dl_121476;
TY121487 Dl_121486;
TY121500 Dl_121499;
TY121512 Dl_121511;
TY121527 Dl_121526;
TY121537 Dl_121536;
TY121550 Dl_121549;
TY121560 Dl_121559;
TY121573 Dl_121572;
TY121584 Dl_121583;
TY121598 Dl_121597;
TY121609 Dl_121608;
TY121623 Dl_121622;
TY121634 Dl_121633;
TY121648 Dl_121647;
TY121660 Dl_121659;
TY121675 Dl_121674;
TY121687 Dl_121686;
TY121702 Dl_121701;
TY121715 Dl_121714;
TY121731 Dl_121730;
TY121744 Dl_121743;
TY121760 Dl_121759;
TY121773 Dl_121772;
TY121789 Dl_121788;
TY121801 Dl_121800;
TY121816 Dl_121815;
TY121828 Dl_121827;
TY121843 Dl_121842;
TY121855 Dl_121854;
TY121870 Dl_121869;
TY121884 Dl_121883;
TY121896 Dl_121895;
TY121911 Dl_121910;
TY121919 Dl_121918;
TY121925 Dl_121924;
TY121935 Dl_121934;
TY121948 Dl_121947;
TY121958 Dl_121957;
TY121971 Dl_121970;
TY121980 Dl_121979;
TY121990 Dl_121989;
TY122002 Dl_122001;
TY122015 Dl_122014;
TY122024 Dl_122023;
TY122036 Dl_122035;
TY122044 Dl_122043;
TY122051 Dl_122050;
TY122058 Dl_122057;
TY122066 Dl_122065;
TY122073 Dl_122072;
TY122080 Dl_122079;
extern TFrame* frameptr_16242;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) + (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU32)(a) - (NU32)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU32) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_18801();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(void, mlstringrgba_122092)(rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, NimStringDesc* s, NU8 r, NU8 g, NU8 b, NU8 a, NI16 linespacing) {
	NI ln;
	nimfr("mlStringRGBA", "gfx.nim")
	nimln(245, "gfx.nim");
	ln = 0;
	{
		NimStringDesc* l_122104;
		NI first_122121;
		NI last_122123;
		l_122104 = 0;
		nimln(325, "strutils.nim");
		first_122121 = 0;
		nimln(326, "strutils.nim");
		last_122123 = 0;
		{
			nimln(327, "strutils.nim");
			while (1) {
				NI TMP152;
				NI TMP153;
				NI TMP154;
				NI TMP155;
				NI TMP156;
				NI32 LOC6;
				{
					nimln(328, "strutils.nim");
					while (1) {
						nimln(328, "strutils.nim");
						nimln(328, "strutils.nim");
						if ((NU)(last_122123) > (NU)(s->Sup.len)) raiseIndexError();
						if (!!((((NU8)(s->data[last_122123])) == ((NU8)(0)) || ((NU8)(s->data[last_122123])) == ((NU8)(13)) || ((NU8)(s->data[last_122123])) == ((NU8)(10))))) goto LA5;
						nimln(328, "strutils.nim");
						last_122123 = addInt(last_122123, 1);
					} LA5: ;
				}
				nimln(329, "strutils.nim");
				nimln(329, "strutils.nim");
				nimln(329, "strutils.nim");
				TMP152 = subInt(last_122123, 1);
				l_122104 = copyStrLast(s, first_122121, (NI32)(TMP152));
				nimln(247, "gfx.nim");
				nimln(247, "gfx.nim");
				nimln(247, "gfx.nim");
				nimln(247, "gfx.nim");
				TMP153 = mulInt(ln, 8);
				TMP154 = addInt(y, ((NI16)chckRange((NI32)(TMP153), ((NI16) -32768), ((NI16) 32767))));
				if (TMP154 < -32768 || TMP154 > 32767) raiseOverflow();
				nimln(247, "gfx.nim");
				TMP155 = mulInt(ln, ((NI) (linespacing)));
				TMP156 = addInt((NI16)(TMP154), ((NI16)chckRange((NI32)(TMP155), ((NI16) -32768), ((NI16) 32767))));
				if (TMP156 < -32768 || TMP156 > 32767) raiseOverflow();
				LOC6 = 0;
				LOC6 = Dl_121957(renderer, x, (NI16)(TMP156), l_122104->data, r, g, b, a);
				nimln(248, "gfx.nim");
				ln = addInt(ln, 1);
				nimln(331, "strutils.nim");
				{
					nimln(331, "strutils.nim");
					if ((NU)(last_122123) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NU8)(s->data[last_122123]) == (NU8)(10))) goto LA9;
					nimln(331, "strutils.nim");
					last_122123 = addInt(last_122123, 1);
				}
				goto LA7;
				LA9: ;
				{
					nimln(332, "strutils.nim");
					if ((NU)(last_122123) > (NU)(s->Sup.len)) raiseIndexError();
					if (!((NU8)(s->data[last_122123]) == (NU8)(13))) goto LA12;
					nimln(333, "strutils.nim");
					last_122123 = addInt(last_122123, 1);
					nimln(334, "strutils.nim");
					{
						nimln(334, "strutils.nim");
						if ((NU)(last_122123) > (NU)(s->Sup.len)) raiseIndexError();
						if (!((NU8)(s->data[last_122123]) == (NU8)(10))) goto LA16;
						nimln(334, "strutils.nim");
						last_122123 = addInt(last_122123, 1);
					}
					LA16: ;
				}
				goto LA7;
				LA12: ;
				{
					nimln(335, "strutils.nim");
					goto LA2;
				}
				LA7: ;
				nimln(336, "strutils.nim");
				first_122121 = last_122123;
			}
		} LA2: ;
	}
	popFrame();
}

N_NIMCALL(void, mlstringrgba_122145)(rendererptrHEX3Aobjecttype107582* renderer, NI16 x, NI16 y, TY13206* s, NU8 r, NU8 g, NU8 b, NU8 a, NI16 linespacing) {
	NI ln;
	nimfr("mlStringRGBA", "gfx.nim")
	nimln(250, "gfx.nim");
	ln = 0;
	{
		nimln(251, "gfx.nim");
		while (1) {
			NI TMP157;
			NI TMP158;
			NI TMP159;
			NI TMP160;
			NI32 LOC3;
			nimln(251, "gfx.nim");
			nimln(251, "gfx.nim");
			if (!(ln < s->Sup.len)) goto LA2;
			nimln(252, "gfx.nim");
			nimln(252, "gfx.nim");
			nimln(252, "gfx.nim");
			nimln(252, "gfx.nim");
			TMP157 = mulInt(ln, 8);
			nimln(252, "gfx.nim");
			TMP158 = mulInt(ln, ((NI) (linespacing)));
			TMP159 = addInt((NI32)(TMP157), (NI32)(TMP158));
			TMP160 = addInt(y, ((NI16)chckRange((NI32)(TMP159), ((NI16) -32768), ((NI16) 32767))));
			if (TMP160 < -32768 || TMP160 > 32767) raiseOverflow();
			if ((NU)(ln) >= (NU)(s->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = Dl_121957(renderer, x, (NI16)(TMP160), s->data[ln]->data, r, g, b, a);
			nimln(253, "gfx.nim");
			ln = addInt(ln, 1);
		} LA2: ;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, sdl2_gfxInit)(void) {
	nimfr("gfx", "gfx.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_gfxDatInit)(void) {
if (!((TMP149 = nimLoadLibrary((NimStringDesc*) &TMP150))
)) nimLoadLibraryError((NimStringDesc*) &TMP151);
	Dl_121228 = (TY121229) nimGetProcAddr(TMP149, "pixelColor");
	Dl_121237 = (TY121238) nimGetProcAddr(TMP149, "pixelRGBA");
	Dl_121249 = (TY121250) nimGetProcAddr(TMP149, "hlineColor");
	Dl_121259 = (TY121260) nimGetProcAddr(TMP149, "hlineRGBA");
	Dl_121272 = (TY121273) nimGetProcAddr(TMP149, "vlineColor");
	Dl_121282 = (TY121283) nimGetProcAddr(TMP149, "vlineRGBA");
	Dl_121295 = (TY121296) nimGetProcAddr(TMP149, "rectangleColor");
	Dl_121306 = (TY121307) nimGetProcAddr(TMP149, "rectangleRGBA");
	Dl_121320 = (TY121321) nimGetProcAddr(TMP149, "roundedRectangleColor");
	Dl_121332 = (TY121333) nimGetProcAddr(TMP149, "roundedRectangleRGBA");
	Dl_121347 = (TY121348) nimGetProcAddr(TMP149, "boxColor");
	Dl_121358 = (TY121359) nimGetProcAddr(TMP149, "boxRGBA");
	Dl_121372 = (TY121373) nimGetProcAddr(TMP149, "roundedBoxColor");
	Dl_121384 = (TY121385) nimGetProcAddr(TMP149, "roundedBoxRGBA");
	Dl_121399 = (TY121400) nimGetProcAddr(TMP149, "lineColor");
	Dl_121410 = (TY121411) nimGetProcAddr(TMP149, "lineRGBA");
	Dl_121424 = (TY121425) nimGetProcAddr(TMP149, "aalineColor");
	Dl_121435 = (TY121436) nimGetProcAddr(TMP149, "aalineRGBA");
	Dl_121449 = (TY121450) nimGetProcAddr(TMP149, "thickLineColor");
	Dl_121461 = (TY121462) nimGetProcAddr(TMP149, "thickLineRGBA");
	Dl_121476 = (TY121477) nimGetProcAddr(TMP149, "circleColor");
	Dl_121486 = (TY121487) nimGetProcAddr(TMP149, "circleRGBA");
	Dl_121499 = (TY121500) nimGetProcAddr(TMP149, "arcColor");
	Dl_121511 = (TY121512) nimGetProcAddr(TMP149, "arcRGBA");
	Dl_121526 = (TY121527) nimGetProcAddr(TMP149, "aacircleColor");
	Dl_121536 = (TY121537) nimGetProcAddr(TMP149, "aacircleRGBA");
	Dl_121549 = (TY121550) nimGetProcAddr(TMP149, "filledCircleColor");
	Dl_121559 = (TY121560) nimGetProcAddr(TMP149, "filledCircleRGBA");
	Dl_121572 = (TY121573) nimGetProcAddr(TMP149, "ellipseColor");
	Dl_121583 = (TY121584) nimGetProcAddr(TMP149, "ellipseRGBA");
	Dl_121597 = (TY121598) nimGetProcAddr(TMP149, "aaellipseColor");
	Dl_121608 = (TY121609) nimGetProcAddr(TMP149, "aaellipseRGBA");
	Dl_121622 = (TY121623) nimGetProcAddr(TMP149, "filledEllipseColor");
	Dl_121633 = (TY121634) nimGetProcAddr(TMP149, "filledEllipseRGBA");
	Dl_121647 = (TY121648) nimGetProcAddr(TMP149, "pieColor");
	Dl_121659 = (TY121660) nimGetProcAddr(TMP149, "pieRGBA");
	Dl_121674 = (TY121675) nimGetProcAddr(TMP149, "filledPieColor");
	Dl_121686 = (TY121687) nimGetProcAddr(TMP149, "filledPieRGBA");
	Dl_121701 = (TY121702) nimGetProcAddr(TMP149, "trigonColor");
	Dl_121714 = (TY121715) nimGetProcAddr(TMP149, "trigonRGBA");
	Dl_121730 = (TY121731) nimGetProcAddr(TMP149, "aatrigonColor");
	Dl_121743 = (TY121744) nimGetProcAddr(TMP149, "aatrigonRGBA");
	Dl_121759 = (TY121760) nimGetProcAddr(TMP149, "filledTrigonColor");
	Dl_121772 = (TY121773) nimGetProcAddr(TMP149, "filledTrigonRGBA");
	Dl_121788 = (TY121789) nimGetProcAddr(TMP149, "polygonColor");
	Dl_121800 = (TY121801) nimGetProcAddr(TMP149, "polygonRGBA");
	Dl_121815 = (TY121816) nimGetProcAddr(TMP149, "aapolygonColor");
	Dl_121827 = (TY121828) nimGetProcAddr(TMP149, "aapolygonRGBA");
	Dl_121842 = (TY121843) nimGetProcAddr(TMP149, "filledPolygonColor");
	Dl_121854 = (TY121855) nimGetProcAddr(TMP149, "filledPolygonRGBA");
	Dl_121869 = (TY121870) nimGetProcAddr(TMP149, "texturedPolygon");
	Dl_121883 = (TY121884) nimGetProcAddr(TMP149, "bezierColor");
	Dl_121895 = (TY121896) nimGetProcAddr(TMP149, "bezierRGBA");
	Dl_121910 = (TY121911) nimGetProcAddr(TMP149, "gfxPrimitivesSetFont");
	Dl_121918 = (TY121919) nimGetProcAddr(TMP149, "gfxPrimitivesSetFontRotation");
	Dl_121924 = (TY121925) nimGetProcAddr(TMP149, "characterColor");
	Dl_121934 = (TY121935) nimGetProcAddr(TMP149, "characterRGBA");
	Dl_121947 = (TY121948) nimGetProcAddr(TMP149, "stringColor");
	Dl_121957 = (TY121958) nimGetProcAddr(TMP149, "stringRGBA");
	Dl_121970 = (TY121971) nimGetProcAddr(TMP149, "rotozoomSurface");
	Dl_121979 = (TY121980) nimGetProcAddr(TMP149, "rotozoomSurfaceXY");
	Dl_121989 = (TY121990) nimGetProcAddr(TMP149, "rotozoomSurfaceSize");
	Dl_122001 = (TY122002) nimGetProcAddr(TMP149, "rotozoomSurfaceSizeXY");
	Dl_122014 = (TY122015) nimGetProcAddr(TMP149, "zoomSurface");
	Dl_122023 = (TY122024) nimGetProcAddr(TMP149, "zoomSurfaceSize");
	Dl_122035 = (TY122036) nimGetProcAddr(TMP149, "shrinkSurface");
	Dl_122043 = (TY122044) nimGetProcAddr(TMP149, "rotateSurface90Degrees");
	Dl_122050 = (TY122051) nimGetProcAddr(TMP149, "SDL_initFramerate");
	Dl_122057 = (TY122058) nimGetProcAddr(TMP149, "SDL_setFramerate");
	Dl_122065 = (TY122066) nimGetProcAddr(TMP149, "SDL_getFramerate");
	Dl_122072 = (TY122073) nimGetProcAddr(TMP149, "SDL_getFramecount");
	Dl_122079 = (TY122080) nimGetProcAddr(TMP149, "SDL_framerateDelay");
}

