/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\sdl2_sdl2.o d:\documents\projects\nim\smport\nimcache\sdl2_sdl2.c */
#define NIM_INTBITS 32
#include "nimbase.h"

#include <string.h>
typedef struct event106171 event106171;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct rendererptrHEX3Aobjecttype106582 rendererptrHEX3Aobjecttype106582;
typedef struct textureptrHEX3Aobjecttype106583 textureptrHEX3Aobjecttype106583;
typedef struct rect106281 rect106281;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct windowptrHEX3Aobjecttype106581 windowptrHEX3Aobjecttype106581;
typedef NU8 TY106356[52];
struct  event106171  {
NI32 Kind;
TY106356 Padding;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY116623) (rendererptrHEX3Aobjecttype106582* renderer, textureptrHEX3Aobjecttype106583* texture, rect106281* srcrect, rect106281* dstrect);
struct rect106281 {
int Field0;
int Field1;
int Field2;
int Field3;
};
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  textureptrHEX3Aobjecttype106583  {
char dummy;
};
typedef N_CDECL_PTR(NI32, TY116273) (int flags);
typedef N_CDECL_PTR(windowptrHEX3Aobjecttype106581*, TY117178) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(rendererptrHEX3Aobjecttype106582*, TY116349) (windowptrHEX3Aobjecttype106581* window, int index, int flags);
typedef N_CDECL_PTR(NI32, TY117617) (event106171* event);
typedef N_CDECL_PTR(NI32, TY116033) (rendererptrHEX3Aobjecttype106582* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY116661) (rendererptrHEX3Aobjecttype106582* renderer);
typedef N_CDECL_PTR(void, TY116678) (rendererptrHEX3Aobjecttype106582* renderer);
typedef N_CDECL_PTR(void, TY116075) (rendererptrHEX3Aobjecttype106582* renderer);
typedef N_CDECL_PTR(void, TY117237) (windowptrHEX3Aobjecttype106581* window);
struct  rendererptrHEX3Aobjecttype106582  {
char dummy;
};
struct  windowptrHEX3Aobjecttype106581  {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP161, "SDL2.dll", 8);
STRING_LITERAL(TMP162, "SDL2.dll", 8);
event106171 defaultevent_118362;
static void* TMP160;
TY116623 Dl_116622;
TNimType NTI106281; /* Rect */
extern TNimType NTI5811; /* cint */
TNimType NTI106583; /* TexturePtr:ObjectType */
TNimType NTI106552; /* TexturePtr */
TY116273 Dl_116272;
TY117178 Dl_117177;
TY116349 Dl_116348;
extern TFrame* frameptr_16242;
TY117617 Dl_117616;
TY116033 Dl_116032;
TY116661 Dl_116660;
TY116678 Dl_116677;
TY116075 Dl_116074;
TY117237 Dl_117236;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

N_NIMCALL(NIM_BOOL, tobool_106665)(NI32 some) {
	NIM_BOOL result;
	nimfr("toBool", "sdl2.nim")
	result = 0;
	nimln(307, "sdl2.nim");
	result = ((NIM_BOOL) (some));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init)(void) {
	event106171 LOC1;
	nimfr("sdl2", "sdl2.nim")
	nimln(1708, "sdl2.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.Kind = ((NI32) 256);
	defaultevent_118362 = LOC1;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit)(void) {
static TNimNode* TMP167[4];
static TNimNode TMP131[6];
NTI106281.size = sizeof(rect106281);
NTI106281.kind = 18;
NTI106281.base = 0;
NTI106281.flags = 3;
TMP167[0] = &TMP131[1];
TMP131[1].kind = 1;
TMP131[1].offset = offsetof(rect106281, Field0);
TMP131[1].typ = (&NTI5811);
TMP131[1].name = "Field0";
TMP167[1] = &TMP131[2];
TMP131[2].kind = 1;
TMP131[2].offset = offsetof(rect106281, Field1);
TMP131[2].typ = (&NTI5811);
TMP131[2].name = "Field1";
TMP167[2] = &TMP131[3];
TMP131[3].kind = 1;
TMP131[3].offset = offsetof(rect106281, Field2);
TMP131[3].typ = (&NTI5811);
TMP131[3].name = "Field2";
TMP167[3] = &TMP131[4];
TMP131[4].kind = 1;
TMP131[4].offset = offsetof(rect106281, Field3);
TMP131[4].typ = (&NTI5811);
TMP131[4].name = "Field3";
TMP131[0].len = 4; TMP131[0].kind = 2; TMP131[0].sons = &TMP167[0];
NTI106281.node = &TMP131[0];
NTI106583.size = sizeof(textureptrHEX3Aobjecttype106583);
NTI106583.kind = 18;
NTI106583.base = 0;
NTI106583.flags = 3;
TMP131[5].len = 0; TMP131[5].kind = 2;
NTI106583.node = &TMP131[5];
NTI106552.size = sizeof(textureptrHEX3Aobjecttype106583*);
NTI106552.kind = 21;
NTI106552.base = (&NTI106583);
NTI106552.flags = 3;
if (!((TMP160 = nimLoadLibrary((NimStringDesc*) &TMP161))
)) nimLoadLibraryError((NimStringDesc*) &TMP162);
	Dl_116622 = (TY116623) nimGetProcAddr(TMP160, "SDL_RenderCopy");
	Dl_116272 = (TY116273) nimGetProcAddr(TMP160, "SDL_Init");
	Dl_117177 = (TY117178) nimGetProcAddr(TMP160, "SDL_CreateWindow");
	Dl_116348 = (TY116349) nimGetProcAddr(TMP160, "SDL_CreateRenderer");
	Dl_117616 = (TY117617) nimGetProcAddr(TMP160, "SDL_PollEvent");
	Dl_116032 = (TY116033) nimGetProcAddr(TMP160, "SDL_SetRenderDrawColor");
	Dl_116660 = (TY116661) nimGetProcAddr(TMP160, "SDL_RenderClear");
	Dl_116677 = (TY116678) nimGetProcAddr(TMP160, "SDL_RenderPresent");
	Dl_116074 = (TY116075) nimGetProcAddr(TMP160, "SDL_DestroyRenderer");
	Dl_117236 = (TY117237) nimGetProcAddr(TMP160, "SDL_DestroyWindow");
}

