/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\sdl2_image.o d:\documents\projects\nim\smport\nimcache\sdl2_image.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct sdlversion106558 sdlversion106558;
typedef struct surface107298 surface107298;
typedef struct rwops115842 rwops115842;
typedef struct textureptrHEX3Aobjecttype106583 textureptrHEX3Aobjecttype106583;
typedef struct rendererptrHEX3Aobjecttype106582 rendererptrHEX3Aobjecttype106582;
typedef struct pixelformat107292 pixelformat107292;
typedef struct rect106281 rect106281;
typedef struct blitmapptrHEX3Aobjecttype107340 blitmapptrHEX3Aobjecttype107340;
typedef struct mem115844 mem115844;
typedef struct palette107290 palette107290;
typedef struct color107288 color107288;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(sdlversion106558*, TY122215) (void);
typedef N_CDECL_PTR(int, TY122221) (int flags);
typedef N_CDECL_PTR(void, TY122227) (void);
typedef N_CDECL_PTR(surface107298*, TY122232) (rwops115842* src, int freesrc, NCSTRING type_122235);
typedef N_CDECL_PTR(surface107298*, TY122240) (NCSTRING file);
typedef N_CDECL_PTR(surface107298*, TY122246) (rwops115842* src, int freesrc);
typedef N_CDECL_PTR(textureptrHEX3Aobjecttype106583*, TY122253) (rendererptrHEX3Aobjecttype106582* renderer, NCSTRING file);
typedef N_CDECL_PTR(textureptrHEX3Aobjecttype106583*, TY122260) (rendererptrHEX3Aobjecttype106582* renderer, rwops115842* src, int freesrc);
typedef N_CDECL_PTR(textureptrHEX3Aobjecttype106583*, TY122268) (rendererptrHEX3Aobjecttype106582* renderer, rwops115842* src, int freesrc, NCSTRING type_122272);
typedef N_CDECL_PTR(int, TY122277) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122283) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122289) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122295) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122301) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122307) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122313) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122319) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122325) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122331) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122337) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122343) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122349) (rwops115842* src);
typedef N_CDECL_PTR(int, TY122355) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122361) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122367) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122373) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122379) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122385) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122391) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122397) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122403) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122409) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122415) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122421) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122427) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122433) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122439) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122445) (rwops115842* src);
typedef N_CDECL_PTR(surface107298*, TY122451) (NCSTRING* xpm);
struct  sdlversion106558  {
NU8 Major;
NU8 Minor;
NU8 Patch;
};
struct rect106281 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  surface107298  {
NU32 Flags;
pixelformat107292* Format;
NI32 W;
NI32 H;
NI32 Pitch;
void* Pixels;
void* Userdata;
NI32 Locked;
void* Lockdata;
rect106281 Cliprect;
blitmapptrHEX3Aobjecttype107340* Map;
int Refcount;
};
typedef struct {
N_NIMCALL_PTR(NI64, ClPrc) (rwops115842* context, void* ClEnv);
void* ClEnv;
} TY115870;
typedef struct {
N_NIMCALL_PTR(NI64, ClPrc) (rwops115842* context, NI64 offset, int whence, void* ClEnv);
void* ClEnv;
} TY115874;
typedef struct {
N_NIMCALL_PTR(size_t, ClPrc) (rwops115842* context, void* destination, size_t size, size_t maxnum, void* ClEnv);
void* ClEnv;
} TY115880;
typedef struct {
N_NIMCALL_PTR(int, ClPrc) (rwops115842* context, void* ClEnv);
void* ClEnv;
} TY115894;
struct  mem115844  {
NU8* Base;
NU8* Here;
NU8* Stop;
};
struct  rwops115842  {
TY115870 Size;
TY115874 Seek;
TY115880 Read;
TY115880 Write;
TY115894 Close;
int Kind;
mem115844 Mem;
};
struct  textureptrHEX3Aobjecttype106583  {
char dummy;
};
struct  rendererptrHEX3Aobjecttype106582  {
char dummy;
};
typedef NU8 TY107322[2];
struct  pixelformat107292  {
NU32 Format;
palette107290* Palette;
NU8 Bitsperpixel;
NU8 Bytesperpixel;
TY107322 Padding;
NU32 Rmask;
NU32 Gmask;
NU32 Bmask;
NU32 Amask;
NU8 Rloss;
NU8 Gloss;
NU8 Bloss;
NU8 Aloss;
NU8 Rshift;
NU8 Gshift;
NU8 Bshift;
NU8 Ashift;
int Refcount;
pixelformat107292* Next;
};
struct  blitmapptrHEX3Aobjecttype107340  {
char dummy;
};
struct  palette107290  {
int Ncolors;
color107288* Colors;
NU32 Version;
int Refcount;
};
struct color107288 {
NU8 Field0;
NU8 Field1;
NU8 Field2;
NU8 Field3;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP157, "SDL2_image.dll", 14);
STRING_LITERAL(TMP158, "SDL2_image.dll", 14);
static void* TMP156;
TY122215 Dl_122214;
TY122221 Dl_122220;
TY122227 Dl_122226;
TY122232 Dl_122231;
TY122240 Dl_122239;
TY122246 Dl_122245;
TY122253 Dl_122252;
TY122260 Dl_122259;
TY122268 Dl_122267;
TY122277 Dl_122276;
TY122283 Dl_122282;
TY122289 Dl_122288;
TY122295 Dl_122294;
TY122301 Dl_122300;
TY122307 Dl_122306;
TY122313 Dl_122312;
TY122319 Dl_122318;
TY122325 Dl_122324;
TY122331 Dl_122330;
TY122337 Dl_122336;
TY122343 Dl_122342;
TY122349 Dl_122348;
TY122355 Dl_122354;
TY122361 Dl_122360;
TY122367 Dl_122366;
TY122373 Dl_122372;
TY122379 Dl_122378;
TY122385 Dl_122384;
TY122391 Dl_122390;
TY122397 Dl_122396;
TY122403 Dl_122402;
TY122409 Dl_122408;
TY122415 Dl_122414;
TY122421 Dl_122420;
TY122427 Dl_122426;
TY122433 Dl_122432;
TY122439 Dl_122438;
TY122445 Dl_122444;
TY122451 Dl_122450;
extern TFrame* frameptr_16242;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit)(void) {
	nimfr("image", "image.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit)(void) {
if (!((TMP156 = nimLoadLibrary((NimStringDesc*) &TMP157))
)) nimLoadLibraryError((NimStringDesc*) &TMP158);
	Dl_122214 = (TY122215) nimGetProcAddr(TMP156, "IMG_Linked_Version");
	Dl_122220 = (TY122221) nimGetProcAddr(TMP156, "IMG_Init");
	Dl_122226 = (TY122227) nimGetProcAddr(TMP156, "IMG_Quit");
	Dl_122231 = (TY122232) nimGetProcAddr(TMP156, "IMG_LoadTyped_RW");
	Dl_122239 = (TY122240) nimGetProcAddr(TMP156, "IMG_Load");
	Dl_122245 = (TY122246) nimGetProcAddr(TMP156, "IMG_Load_RW");
	Dl_122252 = (TY122253) nimGetProcAddr(TMP156, "IMG_LoadTexture");
	Dl_122259 = (TY122260) nimGetProcAddr(TMP156, "IMG_LoadTexture_RW");
	Dl_122267 = (TY122268) nimGetProcAddr(TMP156, "IMG_LoadTextureTyped_RW");
	Dl_122276 = (TY122277) nimGetProcAddr(TMP156, "IMG_isICO");
	Dl_122282 = (TY122283) nimGetProcAddr(TMP156, "IMG_isCUR");
	Dl_122288 = (TY122289) nimGetProcAddr(TMP156, "IMG_isBMP");
	Dl_122294 = (TY122295) nimGetProcAddr(TMP156, "IMG_isGIF");
	Dl_122300 = (TY122301) nimGetProcAddr(TMP156, "IMG_isJPG");
	Dl_122306 = (TY122307) nimGetProcAddr(TMP156, "IMG_isLBM");
	Dl_122312 = (TY122313) nimGetProcAddr(TMP156, "IMG_isPCX");
	Dl_122318 = (TY122319) nimGetProcAddr(TMP156, "IMG_isPNG");
	Dl_122324 = (TY122325) nimGetProcAddr(TMP156, "IMG_isPNM");
	Dl_122330 = (TY122331) nimGetProcAddr(TMP156, "IMG_isTIF");
	Dl_122336 = (TY122337) nimGetProcAddr(TMP156, "IMG_isXCF");
	Dl_122342 = (TY122343) nimGetProcAddr(TMP156, "IMG_isXPM");
	Dl_122348 = (TY122349) nimGetProcAddr(TMP156, "IMG_isXV");
	Dl_122354 = (TY122355) nimGetProcAddr(TMP156, "IMG_isWEBP");
	Dl_122360 = (TY122361) nimGetProcAddr(TMP156, "IMG_LoadICO_RW");
	Dl_122366 = (TY122367) nimGetProcAddr(TMP156, "IMG_LoadCUR_RW");
	Dl_122372 = (TY122373) nimGetProcAddr(TMP156, "IMG_LoadBMP_RW");
	Dl_122378 = (TY122379) nimGetProcAddr(TMP156, "IMG_LoadGIF_RW");
	Dl_122384 = (TY122385) nimGetProcAddr(TMP156, "IMG_LoadJPG_RW");
	Dl_122390 = (TY122391) nimGetProcAddr(TMP156, "IMG_LoadLBM_RW");
	Dl_122396 = (TY122397) nimGetProcAddr(TMP156, "IMG_LoadPCX_RW");
	Dl_122402 = (TY122403) nimGetProcAddr(TMP156, "IMG_LoadPNG_RW");
	Dl_122408 = (TY122409) nimGetProcAddr(TMP156, "IMG_LoadPNM_RW");
	Dl_122414 = (TY122415) nimGetProcAddr(TMP156, "IMG_LoadTGA_RW");
	Dl_122420 = (TY122421) nimGetProcAddr(TMP156, "IMG_LoadTIF_RW");
	Dl_122426 = (TY122427) nimGetProcAddr(TMP156, "IMG_LoadXCF_RW");
	Dl_122432 = (TY122433) nimGetProcAddr(TMP156, "IMG_LoadXPM_RW");
	Dl_122438 = (TY122439) nimGetProcAddr(TMP156, "IMG_LoadXV_RW");
	Dl_122444 = (TY122445) nimGetProcAddr(TMP156, "IMG_LoadWEBP_RW");
	Dl_122450 = (TY122451) nimGetProcAddr(TMP156, "IMG_ReadXPMFromArray");
}

