/* Generated by Nim Compiler v0.10.3 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, i386, gcc */
/* Command for C compiler:
   gcc.exe -c  -w  -ID:\Nim\lib -o d:\documents\projects\nim\smport\nimcache\smgame.o d:\documents\projects\nim\smport\nimcache\smgame.c */
#define NIM_INTBITS 32
#include "nimbase.h"
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tcell45146 tcell45146;
typedef struct TNimType TNimType;
typedef struct tcellseq45162 tcellseq45162;
typedef struct tgcheap47016 tgcheap47016;
typedef struct tcellset45158 tcellset45158;
typedef struct tpagedesc45154 tpagedesc45154;
typedef struct tmemregion27410 tmemregion27410;
typedef struct tsmallchunk26640 tsmallchunk26640;
typedef struct tllchunk27404 tllchunk27404;
typedef struct tbigchunk26642 tbigchunk26642;
typedef struct tintset26617 tintset26617;
typedef struct ttrunk26613 ttrunk26613;
typedef struct tavlnode27408 tavlnode27408;
typedef struct tgcstat47014 tgcstat47014;
typedef struct event106171 event106171;
typedef struct windowptrHEX3Aobjecttype106581 windowptrHEX3Aobjecttype106581;
typedef struct rendererptrHEX3Aobjecttype106582 rendererptrHEX3Aobjecttype106582;
typedef struct scenemanagerHEX3Aobjecttype124006 scenemanagerHEX3Aobjecttype124006;
typedef struct TNimObject TNimObject;
typedef struct TNimNode TNimNode;
typedef struct TY124007 TY124007;
typedef struct sceneHEX3Aobjecttype120016 sceneHEX3Aobjecttype120016;
typedef struct levelsceneHEX3Aobjecttype123006 levelsceneHEX3Aobjecttype123006;
typedef struct mysceneHEX3Aobjecttype121011 mysceneHEX3Aobjecttype121011;
typedef struct tbasechunk26638 tbasechunk26638;
typedef struct tfreecell26630 tfreecell26630;
typedef struct rect106281 rect106281;
typedef struct textureptrHEX3Aobjecttype106583 textureptrHEX3Aobjecttype106583;
typedef N_CDECL_PTR(NI32, TY116273) (int flags);
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  tcell45146  {
NI Refcount;
TNimType* Typ;
};
struct  tcellseq45162  {
NI Len;
NI Cap;
tcell45146** D;
};
struct  tcellset45158  {
NI Counter;
NI Max;
tpagedesc45154* Head;
tpagedesc45154** Data;
};
typedef tsmallchunk26640* TY27422[512];
typedef ttrunk26613* ttrunkbuckets26615[256];
struct  tintset26617  {
ttrunkbuckets26615 Data;
};
struct  tmemregion27410  {
NI Minlargeobj;
NI Maxlargeobj;
TY27422 Freesmallchunks;
tllchunk27404* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk26642* Freechunkslist;
tintset26617 Chunkstarts;
tavlnode27408* Root;
tavlnode27408* Deleted;
tavlnode27408* Last;
tavlnode27408* Freeavlnodes;
};
struct  tgcstat47014  {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct  tgcheap47016  {
void* Stackbottom;
NI Cyclethreshold;
tcellseq45162 Zct;
tcellseq45162 Decstack;
tcellset45158 Cycleroots;
tcellseq45162 Tempstack;
NI Recgclock;
tmemregion27410 Region;
tgcstat47014 Stat;
};
typedef NU8 TY106356[52];
struct  event106171  {
NI32 Kind;
TY106356 Padding;
};
typedef N_CDECL_PTR(windowptrHEX3Aobjecttype106581*, TY117178) (NCSTRING title, int x, int y, int w, int h, NU32 flags);
typedef N_CDECL_PTR(rendererptrHEX3Aobjecttype106582*, TY116349) (windowptrHEX3Aobjecttype106581* window, int index, int flags);
typedef N_NIMCALL_PTR(void, TY3289) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3294) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3289 marker;
TY3294 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  scenemanagerHEX3Aobjecttype124006  {
  TNimObject Sup;
TY124007* Scenes;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI32, TY117617) (event106171* event);
typedef N_CDECL_PTR(NI32, TY116033) (rendererptrHEX3Aobjecttype106582* renderer, NU8 r, NU8 g, NU8 b, NU8 a);
typedef N_CDECL_PTR(int, TY116661) (rendererptrHEX3Aobjecttype106582* renderer);
typedef N_CDECL_PTR(void, TY116678) (rendererptrHEX3Aobjecttype106582* renderer);
typedef N_CDECL_PTR(void, TY116075) (rendererptrHEX3Aobjecttype106582* renderer);
typedef N_CDECL_PTR(void, TY117237) (windowptrHEX3Aobjecttype106581* window);
typedef NI TY26620[16];
struct  tpagedesc45154  {
tpagedesc45154* Next;
NI Key;
TY26620 Bits;
};
struct  tbasechunk26638  {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct  tsmallchunk26640  {
  tbasechunk26638 Sup;
tsmallchunk26640* Next;
tsmallchunk26640* Prev;
tfreecell26630* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct  tllchunk27404  {
NI Size;
NI Acc;
tllchunk27404* Next;
};
struct  tbigchunk26642  {
  tbasechunk26638 Sup;
tbigchunk26642* Next;
tbigchunk26642* Prev;
NI Align;
NF Data;
};
struct  ttrunk26613  {
ttrunk26613* Next;
NI Key;
TY26620 Bits;
};
typedef tavlnode27408* TY27414[2];
struct  tavlnode27408  {
TY27414 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct  windowptrHEX3Aobjecttype106581  {
char dummy;
};
struct  rendererptrHEX3Aobjecttype106582  {
char dummy;
};
struct  sceneHEX3Aobjecttype120016  {
  TNimObject Sup;
};
struct rect106281 {
int Field0;
int Field1;
int Field2;
int Field3;
};
struct  levelsceneHEX3Aobjecttype123006  {
  sceneHEX3Aobjecttype120016 Sup;
rect106281 Drect;
rect106281 Srect;
textureptrHEX3Aobjecttype106583* Myimage;
};
struct  mysceneHEX3Aobjecttype121011  {
  sceneHEX3Aobjecttype120016 Sup;
NimStringDesc* Customvar;
};
struct  tfreecell26630  {
tfreecell26630* Next;
NI Zerofield;
};
struct  textureptrHEX3Aobjecttype106583  {
char dummy;
};
struct TY124007 {
  TGenericSeq Sup;
  sceneHEX3Aobjecttype120016* data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell45146*, usrtocell_48646)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_19001)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_50204)(tcell45146* c);
N_NOINLINE(void, addzct_48617)(tcellseq45162* s, tcell45146* c);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_51023)(tcell45146* c);
static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell45146* c);
static N_INLINE(void, rtladdcycleroot_49425)(tcell45146* c);
N_NOINLINE(void, incl_45867)(tcellset45158* s, tcell45146* cell);
static N_INLINE(void, decref_50604)(tcell45146* c);
N_NIMCALL(void, init_124453)(scenemanagerHEX3Aobjecttype124006* self);
N_NIMCALL(void, load_124241)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(NIM_BOOL, tobool_106665)(NI32 some);
N_NIMCALL(void, events_124391)(scenemanagerHEX3Aobjecttype124006* self, event106171* e);
N_NIMCALL(void, draw_124341)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render);
static N_INLINE(void, destroy_118183)(windowptrHEX3Aobjecttype106581* window);
N_NIMCALL(void, load_123014)(levelsceneHEX3Aobjecttype123006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, load_121032)(mysceneHEX3Aobjecttype121011* self, rendererptrHEX3Aobjecttype106582* render);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NOINLINE(NIM_BOOL, isobjslowpath_22221)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(void, load_120021)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, events_123038)(levelsceneHEX3Aobjecttype123006* self, event106171* e);
N_NIMCALL(void, events_121046)(mysceneHEX3Aobjecttype121011* self, event106171* e);
N_NIMCALL(void, events_120034)(sceneHEX3Aobjecttype120016* self, event106171* e);
N_NIMCALL(void, update_123048)(levelsceneHEX3Aobjecttype123006* self, NF dt);
N_NIMCALL(void, update_121056)(mysceneHEX3Aobjecttype121011* self, NF dt);
N_NIMCALL(void, update_120047)(sceneHEX3Aobjecttype120016* self, NF dt);
N_NIMCALL(void, draw_123058)(levelsceneHEX3Aobjecttype123006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, draw_121066)(mysceneHEX3Aobjecttype121011* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, draw_120060)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(NimStringDesc*, cust_121017)(mysceneHEX3Aobjecttype121011* self);
N_NIMCALL(void, load_124013)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, update_124246)(scenemanagerHEX3Aobjecttype124006* self, NF dt);
N_NIMCALL(void, draw_124296)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render);
N_NIMCALL(void, events_124346)(scenemanagerHEX3Aobjecttype124006* self, event106171* e);
N_NIMCALL(void, init_124396)(scenemanagerHEX3Aobjecttype124006* self);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2Init)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_sdl2DatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sceneInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_sceneDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mysceneInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_mysceneDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageInit)(void);
NIM_EXTERNC N_NOINLINE(void, sdl2_imageDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_levelsceneInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_levelsceneDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_scenemanagerInit)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_scenemanagerDatInit)(void);
NIM_EXTERNC N_NOINLINE(void, smgameInit)(void);
NIM_EXTERNC N_NOINLINE(void, smgameDatInit)(void);
STRING_LITERAL(TMP170, "SillyMeteors", 12);
extern TY116273 Dl_116272;
NI targetwidth_125008;
NI targetheight_125010;
NI windowwidth_125012;
NI windowheight_125014;
NIM_BOOL gameopen_125022;
NimStringDesc* windowname_125023;
extern TFrame* frameptr_16242;
extern tgcheap47016 gch_47044;
event106171 event_125029;
extern event106171 defaultevent_118362;
windowptrHEX3Aobjecttype106581* window_125030;
rendererptrHEX3Aobjecttype106582* render_125031;
extern TY117178 Dl_117177;
extern TY116349 Dl_116348;
scenemanagerHEX3Aobjecttype124006* smanager_125046;
extern TNimType NTI124005; /* SceneManager */
extern TNimType NTI124006; /* SceneManager:ObjectType */
extern TY117617 Dl_117616;
extern TY116033 Dl_116032;
extern TY116661 Dl_116660;
extern TY116678 Dl_116677;
extern TY116075 Dl_116074;
extern TY117237 Dl_117236;
extern TNimType NTI123006; /* LevelScene:ObjectType */
extern TNimType NTI121011; /* MyScene:ObjectType */
extern TNimType NTI120016; /* Scene:ObjectType */
static TNimType* Nim_OfCheck_CACHE1[2];
static TNimType* Nim_OfCheck_CACHE2[2];
static TNimType* Nim_OfCheck_CACHE3[2];
static TNimType* Nim_OfCheck_CACHE4[2];

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_16242 == NIM_NIL)) goto LA4;
		LOC1 = 0;
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_16242).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_16242;
	frameptr_16242 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_19001();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_16242 = (*frameptr_16242).prev;
}

static N_INLINE(tcell45146*, usrtocell_48646)(void* usr) {
	tcell45146* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	nimln(118, "gc.nim");
	result = ((tcell45146*) ((NI)((NU32)(((NI) (usr))) - (NU32)(((NI)sizeof(tcell45146))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_50204)(tcell45146* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(199, "gc.nim");
	addzct_48617((&gch_47044.Zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell45146* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(233, "gc.nim");
	c = usrtocell_48646(p);
	nimln(235, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(236, "gc.nim");
		rtladdzct_50204(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_48667)(tcell45146* c) {
	NIM_BOOL result;
	nimfr("canbeCycleRoot", "gc.nim")
	result = 0;
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	nimln(121, "gc.nim");
	result = !((((*(*c).Typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_49425)(tcell45146* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(189, "gc.nim");
	{
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		nimln(189, "gc.nim");
		if (!!((((NI) ((NI)((*c).Refcount & 3))) == 3))) goto LA3;
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		nimln(139, "gc.nim");
		(*c).Refcount = (NI)((NI)((*c).Refcount & -4) | 3);
		nimln(191, "gc.nim");
		incl_45867((&gch_47044.Cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_51023)(tcell45146* c) {
	nimfr("incRef", "gc.nim")
	nimln(216, "gc.nim");
	nimln(216, "gc.nim");
	(*c).Refcount = (NI)((NU32)((*c).Refcount) + (NU32)(8));
	nimln(219, "gc.nim");
	{
		NIM_BOOL LOC3;
		nimln(219, "gc.nim");
		LOC3 = 0;
		LOC3 = canbecycleroot_48667(c);
		if (!LOC3) goto LA4;
		nimln(220, "gc.nim");
		rtladdcycleroot_49425(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_50604)(tcell45146* c) {
	nimfr("decRef", "gc.nim")
	nimln(206, "gc.nim");
	{
		nimln(167, "gc.nim");
		(*c).Refcount -= 8;
		nimln(168, "gc.nim");
		if (!((NU32)((*c).Refcount) < (NU32)(8))) goto LA3;
		nimln(207, "gc.nim");
		rtladdzct_50204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(208, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_48667(c);
		if (!LOC6) goto LA7;
		nimln(211, "gc.nim");
		rtladdcycleroot_49425(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(244, "gc.nim");
	{
		tcell45146* LOC5;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(244, "gc.nim");
		nimln(244, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_48646(src);
		incref_51023(LOC5);
	}
	LA3: ;
	nimln(245, "gc.nim");
	{
		tcell45146* LOC10;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(245, "gc.nim");
		nimln(245, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_48646((*dest));
		decref_50604(LOC10);
	}
	LA8: ;
	nimln(246, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, destroy_118183)(windowptrHEX3Aobjecttype106581* window) {
	nimfr("destroy", "sdl2.nim")
	nimln(1662, "sdl2.nim");
	Dl_117236(window);
	popFrame();
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(obj == subclass)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!((*obj).base == subclass)) goto LA7;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(cache[(0)- 0] == obj)) goto LA11;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA11: ;
	{
		if (!(cache[(1)- 0] == obj)) goto LA15;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA15: ;
	result = isobjslowpath_22221(obj, subclass, cache);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, load_120029)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("load", "scene.nim")
	nimln(8, "scene.nim");
	{
		nimln(8, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI123006)))) goto LA3;
		nimln(8, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI123006));
		load_123014(((levelsceneHEX3Aobjecttype123006*) (self)), render);
	}
	goto LA1;
	LA3: ;
	{
		nimln(8, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI121011)))) goto LA6;
		nimln(8, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI121011));
		load_121032(((mysceneHEX3Aobjecttype121011*) (self)), render);
	}
	goto LA1;
	LA6: ;
	{
		nimln(8, "scene.nim");
		if (!((self) && (isObjWithCache((*self).Sup.m_type, (&NTI120016), Nim_OfCheck_CACHE1)))) goto LA9;
		nimln(8, "scene.nim");
		load_120021(self, render);
	}
	goto LA1;
	LA9: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(void, events_120042)(sceneHEX3Aobjecttype120016* self, event106171* e) {
	nimfr("events", "scene.nim")
	nimln(14, "scene.nim");
	{
		nimln(14, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI123006)))) goto LA3;
		nimln(14, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI123006));
		events_123038(((levelsceneHEX3Aobjecttype123006*) (self)), e);
	}
	goto LA1;
	LA3: ;
	{
		nimln(14, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI121011)))) goto LA6;
		nimln(14, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI121011));
		events_121046(((mysceneHEX3Aobjecttype121011*) (self)), e);
	}
	goto LA1;
	LA6: ;
	{
		nimln(14, "scene.nim");
		if (!((self) && (isObjWithCache((*self).Sup.m_type, (&NTI120016), Nim_OfCheck_CACHE2)))) goto LA9;
		nimln(14, "scene.nim");
		events_120034(self, e);
	}
	goto LA1;
	LA9: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(void, update_120055)(sceneHEX3Aobjecttype120016* self, NF dt) {
	nimfr("update", "scene.nim")
	nimln(19, "scene.nim");
	{
		nimln(19, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI123006)))) goto LA3;
		nimln(19, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI123006));
		update_123048(((levelsceneHEX3Aobjecttype123006*) (self)), dt);
	}
	goto LA1;
	LA3: ;
	{
		nimln(19, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI121011)))) goto LA6;
		nimln(19, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI121011));
		update_121056(((mysceneHEX3Aobjecttype121011*) (self)), dt);
	}
	goto LA1;
	LA6: ;
	{
		nimln(19, "scene.nim");
		if (!((self) && (isObjWithCache((*self).Sup.m_type, (&NTI120016), Nim_OfCheck_CACHE3)))) goto LA9;
		nimln(19, "scene.nim");
		update_120047(self, dt);
	}
	goto LA1;
	LA9: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(void, draw_120068)(sceneHEX3Aobjecttype120016* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("draw", "scene.nim")
	nimln(23, "scene.nim");
	{
		nimln(23, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI123006)))) goto LA3;
		nimln(23, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI123006));
		draw_123058(((levelsceneHEX3Aobjecttype123006*) (self)), render);
	}
	goto LA1;
	LA3: ;
	{
		nimln(23, "scene.nim");
		if (!((self) && ((*self).Sup.m_type == (&NTI121011)))) goto LA6;
		nimln(23, "scene.nim");
		if (self) chckObj((*self).Sup.m_type, (&NTI121011));
		draw_121066(((mysceneHEX3Aobjecttype121011*) (self)), render);
	}
	goto LA1;
	LA6: ;
	{
		nimln(23, "scene.nim");
		if (!((self) && (isObjWithCache((*self).Sup.m_type, (&NTI120016), Nim_OfCheck_CACHE4)))) goto LA9;
		nimln(23, "scene.nim");
		draw_120060(self, render);
	}
	goto LA1;
	LA9: ;
	LA1: ;
	popFrame();
}

N_NIMCALL(NimStringDesc*, cust_121025)(mysceneHEX3Aobjecttype121011* self) {
	NimStringDesc* result;
	nimfr("cust", "myscene.nim")
{	result = 0;
	nimln(6, "myscene.nim");
	nimln(6, "myscene.nim");
	result = cust_121017(self);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, load_124241)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("load", "scenemanager.nim")
	nimln(9, "scenemanager.nim");
	load_124013(self, render);
	popFrame();
}

N_NIMCALL(void, update_124291)(scenemanagerHEX3Aobjecttype124006* self, NF dt) {
	nimfr("update", "scenemanager.nim")
	nimln(14, "scenemanager.nim");
	update_124246(self, dt);
	popFrame();
}

N_NIMCALL(void, draw_124341)(scenemanagerHEX3Aobjecttype124006* self, rendererptrHEX3Aobjecttype106582* render) {
	nimfr("draw", "scenemanager.nim")
	nimln(19, "scenemanager.nim");
	draw_124296(self, render);
	popFrame();
}

N_NIMCALL(void, events_124391)(scenemanagerHEX3Aobjecttype124006* self, event106171* e) {
	nimfr("events", "scenemanager.nim")
	nimln(24, "scenemanager.nim");
	events_124346(self, e);
	popFrame();
}

N_NIMCALL(void, init_124453)(scenemanagerHEX3Aobjecttype124006* self) {
	nimfr("init", "scenemanager.nim")
	nimln(29, "scenemanager.nim");
	init_124396(self);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit();
	stdlib_parseutilsDatInit();
	stdlib_strutilsDatInit();
	stdlib_macrosDatInit();
	stdlib_unsignedDatInit();
	sdl2_sdl2DatInit();
	HEX00_sceneDatInit();
	HEX00_mysceneDatInit();
	sdl2_imageDatInit();
	HEX00_levelsceneDatInit();
	HEX00_scenemanagerDatInit();
	smgameDatInit();
	stdlib_parseutilsInit();
	stdlib_strutilsInit();
	stdlib_macrosInit();
	stdlib_unsignedInit();
	sdl2_sdl2Init();
	HEX00_sceneInit();
	HEX00_mysceneInit();
	sdl2_imageInit();
	HEX00_levelsceneInit();
	HEX00_scenemanagerInit();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	smgameInit();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, smgameInit)(void) {
	NI32 LOC1;
	NimStringDesc* LOC2;
	scenemanagerHEX3Aobjecttype124006* LOC3;
	nimfr("smgame", "smgame.nim")
	nimln(4, "smgame.nim");
	nimln(4, "smgame.nim");
	LOC1 = 0;
	LOC1 = Dl_116272(((int) 65535));
	nimln(8, "smgame.nim");
	targetwidth_125008 = 1280;
	nimln(9, "smgame.nim");
	targetheight_125010 = 720;
	nimln(10, "smgame.nim");
	windowwidth_125012 = 1280;
	nimln(11, "smgame.nim");
	windowheight_125014 = 720;
	nimln(15, "smgame.nim");
	gameopen_125022 = NIM_TRUE;
	nimln(16, "smgame.nim");
	LOC2 = 0;
	LOC2 = windowname_125023; windowname_125023 = copyStringRC1(((NimStringDesc*) &TMP170));
	if (LOC2) nimGCunrefNoCycle(LOC2);
	nimln(20, "smgame.nim");
	event_125029 = defaultevent_118362;
	nimln(25, "smgame.nim");
	window_125030 = Dl_117177(windowname_125023->data, ((int) 536805376), ((int) 536805376), ((int) (windowwidth_125012)), ((int) (windowheight_125014)), ((int) 4));
	nimln(32, "smgame.nim");
	render_125031 = Dl_116348(window_125030, ((int) -1), ((NI32) 10));
	nimln(36, "smgame.nim");
	LOC3 = 0;
	LOC3 = (scenemanagerHEX3Aobjecttype124006*) newObj((&NTI124005), sizeof(scenemanagerHEX3Aobjecttype124006));
	(*LOC3).Sup.m_type = (&NTI124006);
	asgnRef((void**) (&smanager_125046), LOC3);
	nimln(39, "smgame.nim");
	init_124453(smanager_125046);
	nimln(42, "smgame.nim");
	load_124241(smanager_125046, render_125031);
	{
		nimln(45, "smgame.nim");
		while (1) {
			NI32 LOC14;
			int LOC15;
			nimln(45, "smgame.nim");
			if (!(gameopen_125022 == NIM_TRUE)) goto LA5;
			{
				nimln(48, "smgame.nim");
				while (1) {
					NI32 LOC8;
					NIM_BOOL LOC9;
					nimln(48, "smgame.nim");
					nimln(48, "smgame.nim");
					LOC8 = 0;
					LOC8 = Dl_117616((&event_125029));
					LOC9 = 0;
					LOC9 = tobool_106665(LOC8);
					if (!LOC9) goto LA7;
					nimln(49, "smgame.nim");
					{
						nimln(49, "smgame.nim");
						if (!(event_125029.Kind == ((NI32) 256))) goto LA12;
						nimln(50, "smgame.nim");
						gameopen_125022 = NIM_FALSE;
					}
					LA12: ;
					nimln(53, "smgame.nim");
					events_124391(smanager_125046, (&event_125029));
				} LA7: ;
			}
			nimln(59, "smgame.nim");
			LOC14 = 0;
			LOC14 = Dl_116032(render_125031, ((NU8) 255), ((NU8) 0), ((NU8) 0), ((NU8) 255));
			nimln(60, "smgame.nim");
			LOC15 = 0;
			LOC15 = Dl_116660(render_125031);
			nimln(63, "smgame.nim");
			draw_124341(smanager_125046, render_125031);
			nimln(65, "smgame.nim");
			Dl_116677(render_125031);
		} LA5: ;
	}
	nimln(68, "smgame.nim");
	Dl_116074(render_125031);
	nimln(69, "smgame.nim");
	destroy_118183(window_125030);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, smgameDatInit)(void) {
}

